/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.mguenther.avrosampler.idl.payroll;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Payroll_1_0 {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Payroll_1_0\",\"namespace\":\"net.mguenther.avrosampler.idl.payroll\",\"types\":[{\"type\":\"record\",\"name\":\"Employee_1_0\",\"fields\":[{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"emails\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"boss\",\"type\":[\"null\",\"Employee_1_0\"]}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends Payroll_1_0 {
    public static final org.apache.avro.Protocol PROTOCOL = net.mguenther.avrosampler.idl.payroll.Payroll_1_0.PROTOCOL;
  }
}