/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.mguenther.avrosampler.clientregistry;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class LogoutRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6064365926492558858L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LogoutRequest\",\"namespace\":\"net.mguenther.avrosampler.clientregistry\",\"fields\":[{\"name\":\"clientId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"The identifier for the client.\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** The identifier for the client. */
  @Deprecated public java.lang.String clientId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LogoutRequest() {}

  /**
   * All-args constructor.
   * @param clientId The identifier for the client.
   */
  public LogoutRequest(java.lang.String clientId) {
    this.clientId = clientId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return clientId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: clientId = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'clientId' field.
   * @return The identifier for the client.
   */
  public java.lang.String getClientId() {
    return clientId;
  }

  /**
   * Sets the value of the 'clientId' field.
   * The identifier for the client.
   * @param value the value to set.
   */
  public void setClientId(java.lang.String value) {
    this.clientId = value;
  }

  /**
   * Creates a new LogoutRequest RecordBuilder.
   * @return A new LogoutRequest RecordBuilder
   */
  public static net.mguenther.avrosampler.clientregistry.LogoutRequest.Builder newBuilder() {
    return new net.mguenther.avrosampler.clientregistry.LogoutRequest.Builder();
  }

  /**
   * Creates a new LogoutRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LogoutRequest RecordBuilder
   */
  public static net.mguenther.avrosampler.clientregistry.LogoutRequest.Builder newBuilder(net.mguenther.avrosampler.clientregistry.LogoutRequest.Builder other) {
    return new net.mguenther.avrosampler.clientregistry.LogoutRequest.Builder(other);
  }

  /**
   * Creates a new LogoutRequest RecordBuilder by copying an existing LogoutRequest instance.
   * @param other The existing instance to copy.
   * @return A new LogoutRequest RecordBuilder
   */
  public static net.mguenther.avrosampler.clientregistry.LogoutRequest.Builder newBuilder(net.mguenther.avrosampler.clientregistry.LogoutRequest other) {
    return new net.mguenther.avrosampler.clientregistry.LogoutRequest.Builder(other);
  }

  /**
   * RecordBuilder for LogoutRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LogoutRequest>
    implements org.apache.avro.data.RecordBuilder<LogoutRequest> {

    /** The identifier for the client. */
    private java.lang.String clientId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.mguenther.avrosampler.clientregistry.LogoutRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.clientId)) {
        this.clientId = data().deepCopy(fields()[0].schema(), other.clientId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing LogoutRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(net.mguenther.avrosampler.clientregistry.LogoutRequest other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.clientId)) {
        this.clientId = data().deepCopy(fields()[0].schema(), other.clientId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'clientId' field.
      * The identifier for the client.
      * @return The value.
      */
    public java.lang.String getClientId() {
      return clientId;
    }

    /**
      * Sets the value of the 'clientId' field.
      * The identifier for the client.
      * @param value The value of 'clientId'.
      * @return This builder.
      */
    public net.mguenther.avrosampler.clientregistry.LogoutRequest.Builder setClientId(java.lang.String value) {
      validate(fields()[0], value);
      this.clientId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'clientId' field has been set.
      * The identifier for the client.
      * @return True if the 'clientId' field has been set, false otherwise.
      */
    public boolean hasClientId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'clientId' field.
      * The identifier for the client.
      * @return This builder.
      */
    public net.mguenther.avrosampler.clientregistry.LogoutRequest.Builder clearClientId() {
      clientId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public LogoutRequest build() {
      try {
        LogoutRequest record = new LogoutRequest();
        record.clientId = fieldSetFlags()[0] ? this.clientId : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
