/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.mguenther.avrosampler.log;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Severity {
  INFO, WARN, ERROR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Severity\",\"namespace\":\"net.mguenther.avrosampler.log\",\"symbols\":[\"INFO\",\"WARN\",\"ERROR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
