/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.mguenther.avrosampler.json.gtd;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ItemCreated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1426504044942808963L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ItemCreated\",\"namespace\":\"net.mguenther.avrosampler.json.gtd\",\"fields\":[{\"name\":\"itemId\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"creator\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence itemId;
  @Deprecated public java.lang.CharSequence description;
  @Deprecated public java.lang.CharSequence creator;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ItemCreated() {}

  /**
   * All-args constructor.
   * @param itemId The new value for itemId
   * @param description The new value for description
   * @param creator The new value for creator
   */
  public ItemCreated(java.lang.CharSequence itemId, java.lang.CharSequence description, java.lang.CharSequence creator) {
    this.itemId = itemId;
    this.description = description;
    this.creator = creator;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return itemId;
    case 1: return description;
    case 2: return creator;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: itemId = (java.lang.CharSequence)value$; break;
    case 1: description = (java.lang.CharSequence)value$; break;
    case 2: creator = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'itemId' field.
   * @return The value of the 'itemId' field.
   */
  public java.lang.CharSequence getItemId() {
    return itemId;
  }

  /**
   * Sets the value of the 'itemId' field.
   * @param value the value to set.
   */
  public void setItemId(java.lang.CharSequence value) {
    this.itemId = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'creator' field.
   * @return The value of the 'creator' field.
   */
  public java.lang.CharSequence getCreator() {
    return creator;
  }

  /**
   * Sets the value of the 'creator' field.
   * @param value the value to set.
   */
  public void setCreator(java.lang.CharSequence value) {
    this.creator = value;
  }

  /**
   * Creates a new ItemCreated RecordBuilder.
   * @return A new ItemCreated RecordBuilder
   */
  public static net.mguenther.avrosampler.json.gtd.ItemCreated.Builder newBuilder() {
    return new net.mguenther.avrosampler.json.gtd.ItemCreated.Builder();
  }

  /**
   * Creates a new ItemCreated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ItemCreated RecordBuilder
   */
  public static net.mguenther.avrosampler.json.gtd.ItemCreated.Builder newBuilder(net.mguenther.avrosampler.json.gtd.ItemCreated.Builder other) {
    return new net.mguenther.avrosampler.json.gtd.ItemCreated.Builder(other);
  }

  /**
   * Creates a new ItemCreated RecordBuilder by copying an existing ItemCreated instance.
   * @param other The existing instance to copy.
   * @return A new ItemCreated RecordBuilder
   */
  public static net.mguenther.avrosampler.json.gtd.ItemCreated.Builder newBuilder(net.mguenther.avrosampler.json.gtd.ItemCreated other) {
    return new net.mguenther.avrosampler.json.gtd.ItemCreated.Builder(other);
  }

  /**
   * RecordBuilder for ItemCreated instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ItemCreated>
    implements org.apache.avro.data.RecordBuilder<ItemCreated> {

    private java.lang.CharSequence itemId;
    private java.lang.CharSequence description;
    private java.lang.CharSequence creator;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.mguenther.avrosampler.json.gtd.ItemCreated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.itemId)) {
        this.itemId = data().deepCopy(fields()[0].schema(), other.itemId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.creator)) {
        this.creator = data().deepCopy(fields()[2].schema(), other.creator);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ItemCreated instance
     * @param other The existing instance to copy.
     */
    private Builder(net.mguenther.avrosampler.json.gtd.ItemCreated other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.itemId)) {
        this.itemId = data().deepCopy(fields()[0].schema(), other.itemId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.creator)) {
        this.creator = data().deepCopy(fields()[2].schema(), other.creator);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'itemId' field.
      * @return The value.
      */
    public java.lang.CharSequence getItemId() {
      return itemId;
    }

    /**
      * Sets the value of the 'itemId' field.
      * @param value The value of 'itemId'.
      * @return This builder.
      */
    public net.mguenther.avrosampler.json.gtd.ItemCreated.Builder setItemId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.itemId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'itemId' field has been set.
      * @return True if the 'itemId' field has been set, false otherwise.
      */
    public boolean hasItemId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'itemId' field.
      * @return This builder.
      */
    public net.mguenther.avrosampler.json.gtd.ItemCreated.Builder clearItemId() {
      itemId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }

    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public net.mguenther.avrosampler.json.gtd.ItemCreated.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.description = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public net.mguenther.avrosampler.json.gtd.ItemCreated.Builder clearDescription() {
      description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'creator' field.
      * @return The value.
      */
    public java.lang.CharSequence getCreator() {
      return creator;
    }

    /**
      * Sets the value of the 'creator' field.
      * @param value The value of 'creator'.
      * @return This builder.
      */
    public net.mguenther.avrosampler.json.gtd.ItemCreated.Builder setCreator(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.creator = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'creator' field has been set.
      * @return True if the 'creator' field has been set, false otherwise.
      */
    public boolean hasCreator() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'creator' field.
      * @return This builder.
      */
    public net.mguenther.avrosampler.json.gtd.ItemCreated.Builder clearCreator() {
      creator = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public ItemCreated build() {
      try {
        ItemCreated record = new ItemCreated();
        record.itemId = fieldSetFlags()[0] ? this.itemId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.description = fieldSetFlags()[1] ? this.description : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.creator = fieldSetFlags()[2] ? this.creator : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
