/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.mguenther.avrosampler.json.gtd;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ItemMovedToList extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5566490632541738332L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ItemMovedToList\",\"namespace\":\"net.mguenther.avrosampler.json.gtd\",\"fields\":[{\"name\":\"itemId\",\"type\":\"string\"},{\"name\":\"list\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence itemId;
  @Deprecated public java.lang.CharSequence list;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ItemMovedToList() {}

  /**
   * All-args constructor.
   * @param itemId The new value for itemId
   * @param list The new value for list
   */
  public ItemMovedToList(java.lang.CharSequence itemId, java.lang.CharSequence list) {
    this.itemId = itemId;
    this.list = list;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return itemId;
    case 1: return list;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: itemId = (java.lang.CharSequence)value$; break;
    case 1: list = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'itemId' field.
   * @return The value of the 'itemId' field.
   */
  public java.lang.CharSequence getItemId() {
    return itemId;
  }

  /**
   * Sets the value of the 'itemId' field.
   * @param value the value to set.
   */
  public void setItemId(java.lang.CharSequence value) {
    this.itemId = value;
  }

  /**
   * Gets the value of the 'list' field.
   * @return The value of the 'list' field.
   */
  public java.lang.CharSequence getList() {
    return list;
  }

  /**
   * Sets the value of the 'list' field.
   * @param value the value to set.
   */
  public void setList(java.lang.CharSequence value) {
    this.list = value;
  }

  /**
   * Creates a new ItemMovedToList RecordBuilder.
   * @return A new ItemMovedToList RecordBuilder
   */
  public static net.mguenther.avrosampler.json.gtd.ItemMovedToList.Builder newBuilder() {
    return new net.mguenther.avrosampler.json.gtd.ItemMovedToList.Builder();
  }

  /**
   * Creates a new ItemMovedToList RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ItemMovedToList RecordBuilder
   */
  public static net.mguenther.avrosampler.json.gtd.ItemMovedToList.Builder newBuilder(net.mguenther.avrosampler.json.gtd.ItemMovedToList.Builder other) {
    return new net.mguenther.avrosampler.json.gtd.ItemMovedToList.Builder(other);
  }

  /**
   * Creates a new ItemMovedToList RecordBuilder by copying an existing ItemMovedToList instance.
   * @param other The existing instance to copy.
   * @return A new ItemMovedToList RecordBuilder
   */
  public static net.mguenther.avrosampler.json.gtd.ItemMovedToList.Builder newBuilder(net.mguenther.avrosampler.json.gtd.ItemMovedToList other) {
    return new net.mguenther.avrosampler.json.gtd.ItemMovedToList.Builder(other);
  }

  /**
   * RecordBuilder for ItemMovedToList instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ItemMovedToList>
    implements org.apache.avro.data.RecordBuilder<ItemMovedToList> {

    private java.lang.CharSequence itemId;
    private java.lang.CharSequence list;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.mguenther.avrosampler.json.gtd.ItemMovedToList.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.itemId)) {
        this.itemId = data().deepCopy(fields()[0].schema(), other.itemId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.list)) {
        this.list = data().deepCopy(fields()[1].schema(), other.list);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ItemMovedToList instance
     * @param other The existing instance to copy.
     */
    private Builder(net.mguenther.avrosampler.json.gtd.ItemMovedToList other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.itemId)) {
        this.itemId = data().deepCopy(fields()[0].schema(), other.itemId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.list)) {
        this.list = data().deepCopy(fields()[1].schema(), other.list);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'itemId' field.
      * @return The value.
      */
    public java.lang.CharSequence getItemId() {
      return itemId;
    }

    /**
      * Sets the value of the 'itemId' field.
      * @param value The value of 'itemId'.
      * @return This builder.
      */
    public net.mguenther.avrosampler.json.gtd.ItemMovedToList.Builder setItemId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.itemId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'itemId' field has been set.
      * @return True if the 'itemId' field has been set, false otherwise.
      */
    public boolean hasItemId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'itemId' field.
      * @return This builder.
      */
    public net.mguenther.avrosampler.json.gtd.ItemMovedToList.Builder clearItemId() {
      itemId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'list' field.
      * @return The value.
      */
    public java.lang.CharSequence getList() {
      return list;
    }

    /**
      * Sets the value of the 'list' field.
      * @param value The value of 'list'.
      * @return This builder.
      */
    public net.mguenther.avrosampler.json.gtd.ItemMovedToList.Builder setList(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.list = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'list' field has been set.
      * @return True if the 'list' field has been set, false otherwise.
      */
    public boolean hasList() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'list' field.
      * @return This builder.
      */
    public net.mguenther.avrosampler.json.gtd.ItemMovedToList.Builder clearList() {
      list = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public ItemMovedToList build() {
      try {
        ItemMovedToList record = new ItemMovedToList();
        record.itemId = fieldSetFlags()[0] ? this.itemId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.list = fieldSetFlags()[1] ? this.list : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
