/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.mguenther.avrosampler.json.gtd;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RequiredEnergyAssigned extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8086628240634319280L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RequiredEnergyAssigned\",\"namespace\":\"net.mguenther.avrosampler.json.gtd\",\"fields\":[{\"name\":\"itemId\",\"type\":\"string\"},{\"name\":\"requiredEnergy\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence itemId;
  @Deprecated public int requiredEnergy;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RequiredEnergyAssigned() {}

  /**
   * All-args constructor.
   * @param itemId The new value for itemId
   * @param requiredEnergy The new value for requiredEnergy
   */
  public RequiredEnergyAssigned(java.lang.CharSequence itemId, java.lang.Integer requiredEnergy) {
    this.itemId = itemId;
    this.requiredEnergy = requiredEnergy;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return itemId;
    case 1: return requiredEnergy;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: itemId = (java.lang.CharSequence)value$; break;
    case 1: requiredEnergy = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'itemId' field.
   * @return The value of the 'itemId' field.
   */
  public java.lang.CharSequence getItemId() {
    return itemId;
  }

  /**
   * Sets the value of the 'itemId' field.
   * @param value the value to set.
   */
  public void setItemId(java.lang.CharSequence value) {
    this.itemId = value;
  }

  /**
   * Gets the value of the 'requiredEnergy' field.
   * @return The value of the 'requiredEnergy' field.
   */
  public java.lang.Integer getRequiredEnergy() {
    return requiredEnergy;
  }

  /**
   * Sets the value of the 'requiredEnergy' field.
   * @param value the value to set.
   */
  public void setRequiredEnergy(java.lang.Integer value) {
    this.requiredEnergy = value;
  }

  /**
   * Creates a new RequiredEnergyAssigned RecordBuilder.
   * @return A new RequiredEnergyAssigned RecordBuilder
   */
  public static net.mguenther.avrosampler.json.gtd.RequiredEnergyAssigned.Builder newBuilder() {
    return new net.mguenther.avrosampler.json.gtd.RequiredEnergyAssigned.Builder();
  }

  /**
   * Creates a new RequiredEnergyAssigned RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RequiredEnergyAssigned RecordBuilder
   */
  public static net.mguenther.avrosampler.json.gtd.RequiredEnergyAssigned.Builder newBuilder(net.mguenther.avrosampler.json.gtd.RequiredEnergyAssigned.Builder other) {
    return new net.mguenther.avrosampler.json.gtd.RequiredEnergyAssigned.Builder(other);
  }

  /**
   * Creates a new RequiredEnergyAssigned RecordBuilder by copying an existing RequiredEnergyAssigned instance.
   * @param other The existing instance to copy.
   * @return A new RequiredEnergyAssigned RecordBuilder
   */
  public static net.mguenther.avrosampler.json.gtd.RequiredEnergyAssigned.Builder newBuilder(net.mguenther.avrosampler.json.gtd.RequiredEnergyAssigned other) {
    return new net.mguenther.avrosampler.json.gtd.RequiredEnergyAssigned.Builder(other);
  }

  /**
   * RecordBuilder for RequiredEnergyAssigned instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RequiredEnergyAssigned>
    implements org.apache.avro.data.RecordBuilder<RequiredEnergyAssigned> {

    private java.lang.CharSequence itemId;
    private int requiredEnergy;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.mguenther.avrosampler.json.gtd.RequiredEnergyAssigned.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.itemId)) {
        this.itemId = data().deepCopy(fields()[0].schema(), other.itemId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.requiredEnergy)) {
        this.requiredEnergy = data().deepCopy(fields()[1].schema(), other.requiredEnergy);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RequiredEnergyAssigned instance
     * @param other The existing instance to copy.
     */
    private Builder(net.mguenther.avrosampler.json.gtd.RequiredEnergyAssigned other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.itemId)) {
        this.itemId = data().deepCopy(fields()[0].schema(), other.itemId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.requiredEnergy)) {
        this.requiredEnergy = data().deepCopy(fields()[1].schema(), other.requiredEnergy);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'itemId' field.
      * @return The value.
      */
    public java.lang.CharSequence getItemId() {
      return itemId;
    }

    /**
      * Sets the value of the 'itemId' field.
      * @param value The value of 'itemId'.
      * @return This builder.
      */
    public net.mguenther.avrosampler.json.gtd.RequiredEnergyAssigned.Builder setItemId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.itemId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'itemId' field has been set.
      * @return True if the 'itemId' field has been set, false otherwise.
      */
    public boolean hasItemId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'itemId' field.
      * @return This builder.
      */
    public net.mguenther.avrosampler.json.gtd.RequiredEnergyAssigned.Builder clearItemId() {
      itemId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'requiredEnergy' field.
      * @return The value.
      */
    public java.lang.Integer getRequiredEnergy() {
      return requiredEnergy;
    }

    /**
      * Sets the value of the 'requiredEnergy' field.
      * @param value The value of 'requiredEnergy'.
      * @return This builder.
      */
    public net.mguenther.avrosampler.json.gtd.RequiredEnergyAssigned.Builder setRequiredEnergy(int value) {
      validate(fields()[1], value);
      this.requiredEnergy = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'requiredEnergy' field has been set.
      * @return True if the 'requiredEnergy' field has been set, false otherwise.
      */
    public boolean hasRequiredEnergy() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'requiredEnergy' field.
      * @return This builder.
      */
    public net.mguenther.avrosampler.json.gtd.RequiredEnergyAssigned.Builder clearRequiredEnergy() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public RequiredEnergyAssigned build() {
      try {
        RequiredEnergyAssigned record = new RequiredEnergyAssigned();
        record.itemId = fieldSetFlags()[0] ? this.itemId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.requiredEnergy = fieldSetFlags()[1] ? this.requiredEnergy : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
